name: 'CI'
on:
   push:
      branches:
         - __disabled
   pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
   group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
   cancel-in-progress: true

permissions:
   contents: read

env:
   AUTH_GOOGLE_CLIENT_ID: 'xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com'
   AUTH_GOOGLE_CLIENT_SECRET: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
   AUTH_REDIRECT_URI: 'https://knomii.coach'
   DATABASE_URL: 'mysql://user:password@host:3306/knomii'

jobs:
   lint:
      name: Lint Codebase
      timeout-minutes: 4
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Create and populate .env file
           run: |
              touch .env

              echo AUTH_GOOGLE_CLIENT_ID="$AUTH_GOOGLE_CLIENT_ID" >> .env
              echo AUTH_GOOGLE_CLIENT_SECRET="$AUTH_GOOGLE_CLIENT_SECRET" >> .env
              echo AUTH_REDIRECT_URI="$AUTH_REDIRECT_URI" >> .env
              echo DATABASE_URL="$DATABASE_URL" >> .env

              echo "cat .env"
              cat .env

              echo "ls -a ."
              ls -a .

              echo "ls -a ${{ github.workspace }}"
              ls -a ${{ github.workspace }}
           shell: bash

         - name: Set Node to v18.13.0
           uses: actions/setup-node@v3
           with:
              node-version: v18.13.0

         - name: Get Node version
           id: node
           run: echo "version=$(node -v)" >> $GITHUB_OUTPUT
           #run: echo "::set-output name=version::$(node --v)"

         - uses: pnpm/action-setup@v2
           name: Install pnpm
           with:
              version: 8.6.9
              run_install: false

         - name: Get pnpm store directory
           shell: bash
           run: |
              echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

         - uses: actions/cache@v3
           name: Setup pnpm cache
           with:
              path: ${{ env.STORE_PATH }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                 ${{ runner.os }}-pnpm-store-

         - name: Source .env file
           run: source .env
           shell: bash

         - name: Install dependencies
           run: pnpm install

         - name: Sync generated typings
           run: pnpm run sync

         - name: Lint Prettier
           run: pnpm run lint:format

         - name: Lint Eslint
           run: pnpm run lint:style

         - name: Check for type errors
           run: pnpm run ts
